### ISSUE TITLE
Columns have white background

### ISSUE THREAD

**Issue by IanVaughan** [aalvarado/JiraDarkTheme#19] opened 2021-04-22 10:51 UTC
<img width="566" alt="Screenshot 2021-04-22 at 11 50 20" src="https://user-images.githubusercontent.com/158600/115702645-15555080-a361-11eb-8676-a58d620c6e15.png">

Cool stuff otherwise!

**Comment by IanVaughan** [comment] 2021-04-22 10:52
Same for Pinned fields:

<img width="450" alt="Screenshot 2021-04-22 at 11 52 30" src="https://user-images.githubusercontent.com/158600/115702764-3a49c380-a361-11eb-9152-937a54094417.png">

**Comment by aalvarado** [comment] 2021-04-22 17:48
Maybe I should create a Jira board to be able to reproduce some of this stuff :) . 

Can you tell me in which views I can find these issues so I can reproduce?

**Comment by IanVaughan** [comment] 2021-04-24 11:06
Sorry I dont know how to say which views this are on, its just our standard sprint view.
<img width="251" alt="Screenshot 2021-04-24 at 12 06 04" src="https://user-images.githubusercontent.com/158600/115956579-7a41af80-a4f5-11eb-8bd0-c3b9d5dfd8b1.png">

**Comment by aalvarado** [comment] 2021-04-27 02:05
Haven't been able to reproduce, I can create subtasks but I don't get the same layout as you. I've tried different views but I'm unable to see it, maybe it's an integration?

**Comment by kylejacks0n** [comment] 2021-05-02 15:56
I'm seeing the same thing. Perhaps it's only affecting next-gen projects?

**Comment by aalvarado** [comment] 2021-05-02 19:45
Ill see if i can create a test environment

**Comment by aalvarado** [comment] 2021-05-04 20:54
@kylejacks0n do you know if there are steps to change to next gen? I created a jira test board but I can't that view. I've tried creating a kanban and a scrum board. Those are usually what it seems to be available.

**Comment by aalvarado** [comment] 2021-05-20 17:13
@djones0 Great information, Thank you! 

I created a project in Jira for testing this theme there, I'll make sure to try and test Team managed views too.

Several elements in the Jira frontend have auto generated class names, unfortunately this makes it harder to target some of them.

**Comment by brianbeergod** [comment] 2021-09-30 05:10
I can confirm I see this. I was able to override it by adding 

` .ReactVirtualized__Grid__innerScrollContainer {
        background-color: #555 !important;
    }`

It's not the "pretty" solution, but it does work. 

Before: 
![2021-09-30 01_09_42-PR board - Agile board - Jira](https://user-images.githubusercontent.com/42472382/135391033-c171cb6a-2e1f-4d9b-8453-4a9535dc2165.png)

After:
![2021-09-30 01_09_55-PR board - Agile board - Jira](https://user-images.githubusercontent.com/42472382/135391040-27a8c230-7ed2-4e4b-93a2-7fd2b5bb55cd.png)

**Comment by aalvarado** [comment] 2021-09-30 20:18
I think it's a good solution, would welcome a PR :)

**Comment by brianbeergod** [comment] 2021-10-01 02:01
> I think it's a good solution, would welcome a PR :)

PR created

**Comment by aalvarado** [comment] 2021-10-02 17:02
Thank you all! PR  merged! #32 

Also released a new version

Please reopen if not fixed :)

**Closed by aalvarado** 2021-10-02 17:02 UTC
Labels: bug, help wanted, good first issue
